name: Production

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.4
      with:
        node-version: 16.x

    - name: install dependencies
      run: yarn

    - name: Run build
      run: yarn build
      env:
        REACT_APP_SERVER: ${{ secrets.REACT_APP_SERVER }}
        REACT_APP_REVENUE_PB_LINK: ${{ secrets.REACT_APP_REVENUE_PB_LINK }}
        REACT_APP_PRODUCTIVITY_PB_LINK: ${{ secrets.REACT_APP_PRODUCTIVITY_PB_LINK }}
        REACT_APP_IMPORTEXPORT_PB_LINK: ${{ secrets.REACT_APP_IMPORTEXPORT_PB_LINK }}

    - name: Copy project to AGF
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASS }}
        source: ".,!node_modules"
        target: "~/app/agf-bi"

    - name: Run production scripts
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        port: ${{ secrets.SSH_PORT }}
        password: ${{ secrets.SSH_PASS }}
        script: |
          cd ~/app/agf-bi
          yarn
          pm2 restart agf-bi
